configs:
    - configs/base.yaml

model:
    checkpoint: data/checkpoints/scal3r.pt

model_cfg:
    sampler_cfg:
        use_checkpoint: true
        agg_regator_cfg:
            img_size: 518
            patch_size: 14
            embed_dim: 1024
            frame_use_ttt: false
            global_use_ttt: true
            ttt_layer_idx:
                - 14
                - 17
                - 20
                - 23
            ttt_cfg:
                num_heads: 1
                inter_multi: 4
                base_lr: 0.01
                muon_update_steps: 5
                use_ddp_allreduce: true
                use_modulation: true
            num_global_tokens: 0

val_dataloader_cfg:
    dataset_cfg:
        render_ratio: 1.0
        rot90: null
        proc_max_size: 518
        proc_align_size: 14
        center_crop: true
        focal_ratio: 1.0
        cam_param_type: abs_quat_fov
        use_world_coord: true
